# Generated by Django 4.2 on 2023-08-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_serviceinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_author', models.CharField(max_length=100)),
                ('blog_image', models.ImageField(upload_to='media/images')),
                ('blog_title', models.CharField(max_length=400)),
                ('blog_content', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_image', models.ImageField(upload_to='media/images')),
                ('project_category', models.CharField(max_length=250)),
                ('project_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(upload_to='media/images')),
                ('client_opinion', models.TextField(max_length=400)),
                ('client_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameField(
            model_name='serviceinfo',
            old_name='img',
            new_name='service_image',
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='service_sub_title',
            field=models.TextField(default='sub-title', max_length=300),
        ),
        migrations.AddField(
            model_name='serviceinfo',
            name='service_title',
            field=models.CharField(default='title', max_length=250),
        ),
    ]
