# Generated by Django 4.2 on 2023-08-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_bloginfo_projectinfo_testimonialinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginfo',
            name='blog_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='project_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='serviceinfo',
            name='service_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='testimonialinfo',
            name='client_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
