# Generated by Django 4.2 on 2023-08-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_bloginfo_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='project_link',
            field=models.URLField(default=1),
        ),
    ]
